In [36]:
import os
import pandas as pd
import time

cwd = os.getcwd()

In [37]:
data = pd.read_csv('C:\\Users\\Admin\\Data Analytics Final Project\\all_combined_data.csv')

In [38]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4792283 entries, 0 to 4792282
Data columns (total 17 columns):
 #   Column             Dtype
---  ------             -----
 0   Unnamed: 0         int64
 1   FlightDate         object
 2   UniqueCarrier      object
 3   FlightNum          int64
 4   Origin             object
 5   Dest               object
 6   CRSDepDateTime     object
 7   DepTime            float64
 8   DepDelay           float64
 9   CRSArrDateTime     object
 10  ArrTime            float64
 11  ArrDelay           float64
 12  CRSElapsedTime     int64
 13  ActualElapsedTime  float64
 14  Cancelled          int64
 15  Diverted           int64
 16  Distance           float64
dtypes: float64(6), int64(5), object(6)
memory usage: 621.6+ MB

In [39]:
data.head()

,Unnamed: 0,FlightDate,UniqueCarrier,FlightNum,Origin,Dest,CRSDepDateTime,DepTime,DepDelay,CRSArrDateTime,ArrTime,ArrDelay,CRSElapsedTime,ActualElapsedTime,Cancelled,Diverted,Distance
0,222562,1987-10-02,PI,944,JFK,UCA,1987-10-02 15:00:00,1502.0,2.0,1987-10-02 15:50:00,1547.0,-3.0,50,45.0,0,0,191.0
1,120180,1987-10-24,EA,909,BOS,MCO,1987-10-24 09:40:00,1015.0,35.0,1987-10-24 12:39:00,1308.0,29.0,179,173.0,0,0,1121.0
2,833206,1987-11-14,US,293,LGA,PIT,1987-11-14 08:20:00,820.0,0.0,1987-11-14 09:45:00,935.0,-10.0,85,75.0,0,0,335.0
3,934684,1987-12-20,UA,598,ORD,MIA,1987-12-20 17:52:00,1754.0,2.0,1987-12-20 21:37:00,2137.0,0.0,225,163.0,0,0,1197.0
4,1015922,1987-12-28,NW,250,DTW,CLE,1987-12-28 20:00:00,115.0,315.0,1987-12-28 20:41:00,200.0,319.0,41,45.0,0,0,95.0

In [40]:
list(data.columns)

['Unnamed: 0',
 'FlightDate',
 'UniqueCarrier',
 'FlightNum',
 'Origin',
 'Dest',
 'CRSDepDateTime',
 'DepTime',
 'DepDelay',
 'CRSArrDateTime',
 'ArrTime',
 'ArrDelay',
 'CRSElapsedTime',
 'ActualElapsedTime',
 'Cancelled',
 'Diverted',
 'Distance']

In [41]:
data.drop(['Unnamed: 0'], axis=1, inplace=True)

In [42]:
data.insert(0, 'id', data.index)

In [43]:
data.head()

,id,FlightDate,UniqueCarrier,FlightNum,Origin,Dest,CRSDepDateTime,DepTime,DepDelay,CRSArrDateTime,ArrTime,ArrDelay,CRSElapsedTime,ActualElapsedTime,Cancelled,Diverted,Distance
0,0,1987-10-02,PI,944,JFK,UCA,1987-10-02 15:00:00,1502.0,2.0,1987-10-02 15:50:00,1547.0,-3.0,50,45.0,0,0,191.0
1,1,1987-10-24,EA,909,BOS,MCO,1987-10-24 09:40:00,1015.0,35.0,1987-10-24 12:39:00,1308.0,29.0,179,173.0,0,0,1121.0
2,2,1987-11-14,US,293,LGA,PIT,1987-11-14 08:20:00,820.0,0.0,1987-11-14 09:45:00,935.0,-10.0,85,75.0,0,0,335.0
3,3,1987-12-20,UA,598,ORD,MIA,1987-12-20 17:52:00,1754.0,2.0,1987-12-20 21:37:00,2137.0,0.0,225,163.0,0,0,1197.0
4,4,1987-12-28,NW,250,DTW,CLE,1987-12-28 20:00:00,115.0,315.0,1987-12-28 20:41:00,200.0,319.0,41,45.0,0,0,95.0

In [44]:
data.isnull().sum()

id                   0
FlightDate           0
UniqueCarrier        0
FlightNum            0
Origin               0
Dest                 0
CRSDepDateTime       0
DepTime              0
DepDelay             0
CRSArrDateTime       0
ArrTime              0
ArrDelay             0
CRSElapsedTime       0
ActualElapsedTime    0
Cancelled            0
Diverted             0
Distance             0
dtype: int64

In [45]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4792283 entries, 0 to 4792282
Data columns (total 17 columns):
 #   Column             Dtype
---  ------             -----
 0   id                 int64
 1   FlightDate         object
 2   UniqueCarrier      object
 3   FlightNum          int64
 4   Origin             object
 5   Dest               object
 6   CRSDepDateTime     object
 7   DepTime            float64
 8   DepDelay           float64
 9   CRSArrDateTime     object
 10  ArrTime            float64
 11  ArrDelay           float64
 12  CRSElapsedTime     int64
 13  ActualElapsedTime  float64
 14  Cancelled          int64
 15  Diverted           int64
 16  Distance           float64
dtypes: float64(6), int64(5), object(6)
memory usage: 621.6+ MB

In [46]:
data['FlightDate'] = pd.to_datetime(data['FlightDate'])
data['CRSDepDateTime'] = pd.to_datetime(data['CRSDepDateTime'])
data['CRSArrDateTime'] = pd.to_datetime(data['CRSArrDateTime'])

In [47]:
data['ArrTime'] = data['ArrTime'].astype(int)
data['ArrTime'] = data['ArrTime'].astype(str)
data['ArrTime'] = data['ArrTime'].str.zfill(4)
data['ArrTime'].head()
data['ArrTime'] = data['ArrTime'].astype(int)

In [48]:
data['DepTime'] = data['DepTime'].astype(int)
data['DepTime'] = data['DepTime'].astype(str)
data['DepTime'] = data['DepTime'].str.zfill(4)
data['DepTime'].head()
data['DepTime'] = data['DepTime'].astype(int)

In [49]:
data.head()

,id,FlightDate,UniqueCarrier,FlightNum,Origin,Dest,CRSDepDateTime,DepTime,DepDelay,CRSArrDateTime,ArrTime,ArrDelay,CRSElapsedTime,ActualElapsedTime,Cancelled,Diverted,Distance
0,0,1987-10-02,PI,944,JFK,UCA,1987-10-02 15:00:00,1502,2.0,1987-10-02 15:50:00,1547,-3.0,50,45.0,0,0,191.0
1,1,1987-10-24,EA,909,BOS,MCO,1987-10-24 09:40:00,1015,35.0,1987-10-24 12:39:00,1308,29.0,179,173.0,0,0,1121.0
2,2,1987-11-14,US,293,LGA,PIT,1987-11-14 08:20:00,820,0.0,1987-11-14 09:45:00,935,-10.0,85,75.0,0,0,335.0
3,3,1987-12-20,UA,598,ORD,MIA,1987-12-20 17:52:00,1754,2.0,1987-12-20 21:37:00,2137,0.0,225,163.0,0,0,1197.0
4,4,1987-12-28,NW,250,DTW,CLE,1987-12-28 20:00:00,115,315.0,1987-12-28 20:41:00,200,319.0,41,45.0,0,0,95.0

In [50]:
data['DepDelay'] = data['DepDelay'].astype(int)
data['ArrDelay'] = data['ArrDelay'].astype(int)
data['ActualElapsedTime'] = data['ActualElapsedTime'].astype(int)
data['DepTime'] = data['DepTime'].astype(int)

In [51]:
data.head()

,id,FlightDate,UniqueCarrier,FlightNum,Origin,Dest,CRSDepDateTime,DepTime,DepDelay,CRSArrDateTime,ArrTime,ArrDelay,CRSElapsedTime,ActualElapsedTime,Cancelled,Diverted,Distance
0,0,1987-10-02,PI,944,JFK,UCA,1987-10-02 15:00:00,1502,2,1987-10-02 15:50:00,1547,-3,50,45,0,0,191.0
1,1,1987-10-24,EA,909,BOS,MCO,1987-10-24 09:40:00,1015,35,1987-10-24 12:39:00,1308,29,179,173,0,0,1121.0
2,2,1987-11-14,US,293,LGA,PIT,1987-11-14 08:20:00,820,0,1987-11-14 09:45:00,935,-10,85,75,0,0,335.0
3,3,1987-12-20,UA,598,ORD,MIA,1987-12-20 17:52:00,1754,2,1987-12-20 21:37:00,2137,0,225,163,0,0,1197.0
4,4,1987-12-28,NW,250,DTW,CLE,1987-12-28 20:00:00,115,315,1987-12-28 20:41:00,200,319,41,45,0,0,95.0

In [52]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4792283 entries, 0 to 4792282
Data columns (total 17 columns):
 #   Column             Dtype
---  ------             -----
 0   id                 int64
 1   FlightDate         datetime64[ns]
 2   UniqueCarrier      object
 3   FlightNum          int64
 4   Origin             object
 5   Dest               object
 6   CRSDepDateTime     datetime64[ns]
 7   DepTime            int32
 8   DepDelay           int32
 9   CRSArrDateTime     datetime64[ns]
 10  ArrTime            int32
 11  ArrDelay           int32
 12  CRSElapsedTime     int64
 13  ActualElapsedTime  int32
 14  Cancelled          int64
 15  Diverted           int64
 16  Distance           float64
dtypes: datetime64[ns](3), float64(1), int32(5), int64(5), object(3)
memory usage: 530.2+ MB

In [54]:
cwd = os.getcwd()
data.to_csv(cwd+ "/flight_data_subset.csv", index=False)